### ISSUE TITLE
name 'pyLMS7002Soapy' is not defined

### ISSUE THREAD

**Issue by miloshev** [myriadrf/pyLMS7002Soapy#4]
When i try to run python3 measureVNA_900 i get:
:~/pyLMS7002Soapy/examples$ python3 measureVNA_900M.py test
Searching for LimeSDR... Traceback (most recent call last):
  File "measureVNA_900M.py", line 143, in <module>
    limeSDR = pyLMS7002Soapy(0)
NameError: name 'pyLMS7002Soapy' is not defined

My Limesdr mini works with Soapy and GNU radio without issues and pyLMS7002Soapy library imports without errors.
Any ideas?

**Comment by 9600** [comment]
The module cannot be found, probably because it's written for Python 2 and so you would need to use this.

**Comment by miloshev** [comment]
I have built it in python3 
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyLMS7002Soapy import *
>>> sdr = pyLMS7002Soapy(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pyLMS7002Soapy' is not defined

**Comment by 9600** [comment]
OK, but we don't support Python 3.

**Comment by miloshev** [comment]
Ah, Ok. But in python 2.7 i get message that SoapySDR module is missing. Can you please tell me how to install it, as i have ran through 10 different install instructions with no success.

**Comment by 9600** [comment]
If you are running Ubuntu (and possibly Debian etc) you can just:

$ sudo apt-get install python-soapysdr

Or build from source. See the SoapySDR documentation. 

https://github.com/pothosware/SoapySDR/wiki

**Comment by miloshev** [comment]
Thanks, I have reinstalled all packages an now it works

**Comment by 9600** [comment]
Good to hear!
